peers:
    router:
        name: Crossbar
        host: localhost
        port: 8080
        realm: realm1
        roles: {
                    'roles': {
                        'subscriber': {},
                        'publisher': {},
                    },
                }
